.PHONY: .

help:  ## This help
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

install: ## instala dependencias do pacote
	@poetry install

build: ## build the package 
	@poetry build -f wheel

black:
	poetry run black ./